name: Feature Request
description: Request new core functionality to be added to Huppo.
title: "[FEATURE] <title>"
labels: ["Feature"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search for similar Feature requests to make sure you are not creating a duplicate request.
    options:
    - label: I have searched the existing issues.
      required: true
- type: textarea
  attributes:
    label: Description Of Feature
    description: Please provide a brief description of what this feature would do and what benefit would it provide.
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us a better understanding of what you want added/ changed?

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
